### ISSUE TITLE
[BUG] Version 4.5.X fails oidc authentication with authelia (earlier version works).

### ISSUE THREAD

**Issue by mwinters-stuff** [owncloud/android#4575]
### Actual behaviour
- after the upgrade, connection to the server fails with wanting to login, after authelia authenticates we get a failure to authenticate on the application.
- clear the app settings, and try to reconnect. authelia will show and authenticates but there is an authentication failure.

### Expected behaviour
- Should be able to login with authelia.
- Downgrading to the prior minor version and I can reconnect and it works fine.
 
### Steps to reproduce
1. Have authelia installed, and configured for oics authentication
Eg, from the authelia helm-chart
```
                        - client_id: owncloud-ocis-web
                          client_name: ownCloud web client
                          public: true
                          scopes:
                            - openid
                            - groups
                            - profile
                            - email
                            - offline_access
                          redirect_uris:
                            - https://test.someplace.org.nz/
                            - https://test.someplace.org.nz/oidc-callback.html
                            - https://test.someplace.org.nz/oidc-silent-redirect.html
                          token_endpoint_auth_method: none
                          revocation_endpoint_auth_method: none
                          introspection_endpoint_auth_method: none
                          pushed_authorization_request_endpoint_auth_method: none
                          pushed_authorization_request_endpoint_auth_signing_alg: RS256
                        - client_id: xdXOt13JKxym1B1QcEncf2XDkLAexMBFwiT9j6EfhhHFJhs2KM9jbjTmf8JBXE69
                          client_name: ownCloud desktop client
                          # Well-known secret hashed
                          client_secret: $pbkdf2-sha512$310000$FXcw/AEqjuuNGbmd9mtchw$grhdAMjBBG4HMIitBU57LjiCWa7xKXHBLV5e4d6G.WUNQz2p/ib46UBGP.ZOhwM8v.o0B/r7cQFmIIFizYDTog
                          scopes:
                            - openid
                            - groups
                            - profile
                            - email
                            - offline_access
                          redirect_uris:
                            - http://127.0.0.1
                            - http://localhost
                          allow_multiple_auth_methods: true
                          grant_types:
                            - refresh_token
                            - authorization_code
                          response_types:
                            - code
                        - client_id: e4rAsNUSIUs0lF4nbv9FmCeUkTlV9GdgTLDH1b5uie7syb90SzEVrbN7HIpmWJeD
                          client_name: ownCloud Android app
                          # Well-known secret hashed
                          client_secret: $pbkdf2-sha512$310000$4/vF.LuupptyrFYNyHaaOQ$HqXhAIfKMk9GCMZhQqco4F03O44TtgsJDdv/7p0AfDnzWFynbVhgXUD.zRhkD8xhT4jt5Rsdcnk4U1eoaCppEg
                          scopes:
                            - openid
                            - groups
                            - profile
                            - email
                            - offline_access
                          redirect_uris:
                            - oc://android.owncloud.com
                          allow_multiple_auth_methods: true
                          grant_types:
                            - refresh_token
                            - authorization_code
                          response_types:
                            - code

```
2. Install V4.5.0 or V4.5.1
3. Authenticate on the web app - this will work.
4. Authenticate on the android app, this will fail.

Can this problem be reproduced with the official owncloud server?
(url: https://ocis.ocis.master.owncloud.works, user: einstein, password: relativity)

### Environment data
Android version: 14

Device model:  Samsung A34

Stock or customized system: Stock

ownCloud app version: 4.5.x

ownCloud server version: 7.1.2 

#### Authelia server error log
```
time="2025-04-17T12:59:42+12:00" level=debug msg="User Info Request with id '96f59b68-4e77-42f9-b30f-820325d206fc' is being processed" method=GET path=/api/oidc/userinfo remote_ip=192.168.10.1
time="2025-04-17T12:59:43+12:00" level=debug msg="Check authorization of subject username=mathew groups=admin,admins,calibreweb,everybody,filebrowser,files,gitea-admins,gitea-users,grafanaAdmin,jenkins,lldap_admin,local-web,openhab,owncloud,pihole,proxmox,spaceadmin,syncthing,transmission,user ip=192.168.1.121 and object https://pgadmin.winters.org.nz/sqleditor/status/7790164 (method GET)."
time="2025-04-17T12:59:43+12:00" level=debug msg="User Info Request with id '96f59b68-4e77-42f9-b30f-820325d206fc' on client with id 'xdXOt13JKxym1B1QcEncf2XDkLAexMBFwiT9j6EfhhHFJhs2KM9jbjTmf8JBXE69' is being returned unsigned as per the registered client configuration" method=GET path=/api/oidc/userinfo remote_ip=192.168.10.1
time="2025-04-17T12:59:43+12:00" level=debug msg="User Info Request with id '96f59b68-4e77-42f9-b30f-820325d206fc' on client with id 'xdXOt13JKxym1B1QcEncf2XDkLAexMBFwiT9j6EfhhHFJhs2KM9jbjTmf8JBXE69' was successfully processed" method=GET path=/api/oidc/userinfo remote_ip=192.168.10.1
time="2025-04-17T12:59:51+12:00" level=debug msg="Mark 1FA authentication attempt made by user 'mathew'" method=POST path=/api/firstfactor remote_ip=192.168.1.70
time="2025-04-17T12:59:51+12:00" level=debug msg="Successful 1FA authentication attempt made by user 'mathew'" method=POST path=/api/firstfactor remote_ip=192.168.1.70
time="2025-04-17T12:59:52+12:00" level=warning msg="OpenID Connect client 'e4rAsNUSIUs0lF4nbv9FmCeUkTlV9GdgTLDH1b5uie7syb90SzEVrbN7HIpmWJeD' requires 2FA, cannot be redirected yet" method=POST path=/api/firstfactor remote_ip=192.168.1.70
time="2025-04-17T12:59:58+12:00" level=error msg="Request timeout occurred while handling request from client." error="read tcp 10.42.3.30:9091->10.42.7.155:33784: i/o timeout" method=GET path=/ remote_ip=10.42.7.155 stack="github.com/authelia/authelia/v4/internal/server/handlers.go:92 New.handleError.func2\ngithub.com/valyala/fasthttp@v1.59.0/server.go:2872             (*Server).writeErrorResponse\ngithub.com/valyala/fasthttp@v1.59.0/server.go:2309             (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.59.0/workerpool.go:225          (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.59.0/workerpool.go:197          (*workerPool).getCh.func1\nruntime/asm_amd64.s:1700                                       goexit" status_code=408
time="2025-04-17T13:00:08+12:00" level=debug msg="Authorization Request with id '47f0c528-2c30-4c07-9611-0d6ac38e2e3e' on client with id 'e4rAsNUSIUs0lF4nbv9FmCeUkTlV9GdgTLDH1b5uie7syb90SzEVrbN7HIpmWJeD' is being processed" method=GET path=/api/oidc/authorization remote_ip=192.168.1.70
time="2025-04-17T13:00:08+12:00" level=debug msg="Authorization Request with id '47f0c528-2c30-4c07-9611-0d6ac38e2e3e' on client with id 'e4rAsNUSIUs0lF4nbv9FmCeUkTlV9GdgTLDH1b5uie7syb90SzEVrbN7HIpmWJeD' using consent mode 'explicit' proceeding to generate a new consent session" method=GET path=/api/oidc/authorization remote_ip=192.168.1.70
time="2025-04-17T13:00:08+12:00" level=debug msg="Authorization Request with id '47f0c528-2c30-4c07-9611-0d6ac38e2e3e' on client with id 'e4rAsNUSIUs0lF4nbv9FmCeUkTlV9GdgTLDH1b5uie7syb90SzEVrbN7HIpmWJeD' is not being redirected for reauthentication" authenticated_at="2025-04-17 00:59:52 +0000 UTC" method=GET path=/api/oidc/authorization prompt="select_account consent" remote_ip=192.168.1.70 requested_at="2025-04-17 01:00:08.862273333 +0000 UTC"
time="2025-04-17T13:00:08+12:00" level=debug msg="Authorization Request with id '47f0c528-2c30-4c07-9611-0d6ac38e2e3e' on client with id 'e4rAsNUSIUs0lF4nbv9FmCeUkTlV9GdgTLDH1b5uie7syb90SzEVrbN7HIpmWJeD' using consent mode 'explicit' authentication level 'one_factor' is insufficient for client level 'two_factor'" method=GET path=/api/oidc/authorization remote_ip=192.168.1.70
time="2025-04-17T13:00:08+12:00" level=debug msg="Authorization Request with id '47f0c528-2c30-4c07-9611-0d6ac38e2e3e' on client with id 'e4rAsNUSIUs0lF4nbv9FmCeUkTlV9GdgTLDH1b5uie7syb90SzEVrbN7HIpmWJeD' using consent mode 'explicit' is being redirected to 'https://auth.winters.org.nz/?workflow=openid_connect&workflow_id=bbed05d3-243b-44a0-9d10-e1441259f239'" method=GET path=/api/oidc/authorization remote_ip=192.168.1.70
time="2025-04-17T13:00:12+12:00" level=debug msg="Mark TOTP authentication attempt made by user 'mathew'" method=POST path=/api/secondfactor/totp remote_ip=192.168.1.70
time="2025-04-17T13:00:12+12:00" level=debug msg="Successful TOTP authentication attempt made by user 'mathew'" method=POST path=/api/secondfactor/totp remote_ip=192.168.1.70emote_ip=192.168.1.70
time="2025-04-17T13:00:13+12:00" level=debug msg="Check authorization of subject username=mathew groups=admin,admins,calibreweb,everybody,filebrowser,files,gitea-admins,gitea-users,grafanaAdmin,jenkins,lldap_admin,local-web,openhab,owncloud,pihole,proxmox,spaceadmin,syncthing,transmission,user ip=192.168.1.121 and object https://pgadmin.winters.org.nz/sqleditor/status/7790164 (method GET)."
time="2025-04-17T13:00:13+12:00" level=debug msg="Check authorization of subject username=mathew groups=admin,admins,calibreweb,everybody,filebrowser,files,gitea-admins,gitea-users,grafanaAdmin,jenkins,lldap_admin,local-web,openhab,owncloud,pihole,proxmox,spaceadmin,syncthing,transmission,user ip=192.168.1.121 and object https://pgadmin.winters.org.nz/sqleditor/status/5375415 (method GET)."
time="2025-04-17T13:00:13+12:00" level=debug msg="User Info Request with id '920b028e-306d-4efc-93dc-d7969bb72ff7' is being processed" method=GET path=/api/oidc/userinfo remote_ip=192.168.10.1
time="2025-04-17T13:00:14+12:00" level=debug msg="Authorization Request with id '674c5ed0-6ed0-4e13-aab9-f8ead53c2592' on client with id 'e4rAsNUSIUs0lF4nbv9FmCeUkTlV9GdgTLDH1b5uie7syb90SzEVrbN7HIpmWJeD' is being processed" method=GET path=/api/oidc/authorization remote_ip=192.168.1.70
time="2025-04-17T13:00:14+12:00" level=debug msg="User Info Request with id '920b028e-306d-4efc-93dc-d7969bb72ff7' on client with id 'xdXOt13JKxym1B1QcEncf2XDkLAexMBFwiT9j6EfhhHFJhs2KM9jbjTmf8JBXE69' is being returned unsigned as per the registered client configuration" method=GET path=/api/oidc/userinfo remote_ip=192.168.10.1
time="2025-04-17T13:00:14+12:00" level=debug msg="User Info Request with id '920b028e-306d-4efc-93dc-d7969bb72ff7' on client with id 'xdXOt13JKxym1B1QcEncf2XDkLAexMBFwiT9j6EfhhHFJhs2KM9jbjTmf8JBXE69' was successfully processed" method=GET path=/api/oidc/userinfo remote_ip=192.168.10.1
time="2025-04-17T13:00:14+12:00" level=debug msg="Authorization Request with id '674c5ed0-6ed0-4e13-aab9-f8ead53c2592' on client with id 'e4rAsNUSIUs0lF4nbv9FmCeUkTlV9GdgTLDH1b5uie7syb90SzEVrbN7HIpmWJeD' was successfully processed, proceeding to build Authorization Response" method=GET path=/api/oidc/authorization remote_ip=192.168.1.70
time="2025-04-17T13:00:15+12:00" level=debug msg="Check authorization of subject username=mathew groups=admin,admins,calibreweb,everybody,filebrowser,files,gitea-admins,gitea-users,grafanaAdmin,jenkins,lldap_admin,local-web,openhab,owncloud,pihole,proxmox,spaceadmin,syncthing,transmission,user ip=192.168.1.121 and object https://pgadmin.winters.org.nz/sqleditor/status/7790164 (method GET)."
time="2025-04-17T13:00:15+12:00" level=error msg="Access Request failed with error: The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. Client Authentication failed with more than one known authentication method included in the request which is not permitted. The registered client with id 'e4rAsNUS
```

#### ownCloud log (data/owncloud.log)
```
Log attached.

```
